language: java
jdk: oraclejdk8
script: mvn install -f bugsy/pom.xml

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  
after_failure: cat "/home/travis/build/opcoach/jagsy/bugsy/com.opcoach.bugsy.xtext.ui.tests/target/work/data/.metadata/.log"
