/**
 * generated by Xtext 2.12.0
 */
package com.opcoach.bugsy.xtext.bugsDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Relation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.opcoach.bugsy.xtext.bugsDsl.Relation#getName <em>Name</em>}</li>
 *   <li>{@link com.opcoach.bugsy.xtext.bugsDsl.Relation#getRelationType <em>Relation Type</em>}</li>
 *   <li>{@link com.opcoach.bugsy.xtext.bugsDsl.Relation#getLeftExpr <em>Left Expr</em>}</li>
 * </ul>
 *
 * @see com.opcoach.bugsy.xtext.bugsDsl.BugsDslPackage#getRelation()
 * @model
 * @generated
 */
public interface Relation extends Instruction
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.opcoach.bugsy.xtext.bugsDsl.BugsDslPackage#getRelation_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.opcoach.bugsy.xtext.bugsDsl.Relation#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Relation Type</b></em>' attribute.
   * The literals are from the enumeration {@link com.opcoach.bugsy.xtext.bugsDsl.RelationType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Relation Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Relation Type</em>' attribute.
   * @see com.opcoach.bugsy.xtext.bugsDsl.RelationType
   * @see #setRelationType(RelationType)
   * @see com.opcoach.bugsy.xtext.bugsDsl.BugsDslPackage#getRelation_RelationType()
   * @model
   * @generated
   */
  RelationType getRelationType();

  /**
   * Sets the value of the '{@link com.opcoach.bugsy.xtext.bugsDsl.Relation#getRelationType <em>Relation Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Relation Type</em>' attribute.
   * @see com.opcoach.bugsy.xtext.bugsDsl.RelationType
   * @see #getRelationType()
   * @generated
   */
  void setRelationType(RelationType value);

  /**
   * Returns the value of the '<em><b>Left Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Left Expr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left Expr</em>' containment reference.
   * @see #setLeftExpr(Operation)
   * @see com.opcoach.bugsy.xtext.bugsDsl.BugsDslPackage#getRelation_LeftExpr()
   * @model containment="true"
   * @generated
   */
  Operation getLeftExpr();

  /**
   * Sets the value of the '{@link com.opcoach.bugsy.xtext.bugsDsl.Relation#getLeftExpr <em>Left Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left Expr</em>' containment reference.
   * @see #getLeftExpr()
   * @generated
   */
  void setLeftExpr(Operation value);

} // Relation
