/**
 * generated by Xtext 2.12.0
 */
package com.opcoach.bugsy.xtext.bugsDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Array Range</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.opcoach.bugsy.xtext.bugsDsl.ArrayRange#getLow <em>Low</em>}</li>
 *   <li>{@link com.opcoach.bugsy.xtext.bugsDsl.ArrayRange#getHigh <em>High</em>}</li>
 * </ul>
 *
 * @see com.opcoach.bugsy.xtext.bugsDsl.BugsDslPackage#getArrayRange()
 * @model
 * @generated
 */
public interface ArrayRange extends EObject
{
  /**
   * Returns the value of the '<em><b>Low</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Low</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Low</em>' attribute.
   * @see #setLow(String)
   * @see com.opcoach.bugsy.xtext.bugsDsl.BugsDslPackage#getArrayRange_Low()
   * @model
   * @generated
   */
  String getLow();

  /**
   * Sets the value of the '{@link com.opcoach.bugsy.xtext.bugsDsl.ArrayRange#getLow <em>Low</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Low</em>' attribute.
   * @see #getLow()
   * @generated
   */
  void setLow(String value);

  /**
   * Returns the value of the '<em><b>High</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>High</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>High</em>' attribute.
   * @see #setHigh(String)
   * @see com.opcoach.bugsy.xtext.bugsDsl.BugsDslPackage#getArrayRange_High()
   * @model
   * @generated
   */
  String getHigh();

  /**
   * Sets the value of the '{@link com.opcoach.bugsy.xtext.bugsDsl.ArrayRange#getHigh <em>High</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>High</em>' attribute.
   * @see #getHigh()
   * @generated
   */
  void setHigh(String value);

} // ArrayRange
