/**
 * generated by Xtext 2.12.0
 */
package com.opcoach.bugsy.xtext.bugsDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Array Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.opcoach.bugsy.xtext.bugsDsl.ArrayFunction#getOperation <em>Operation</em>}</li>
 *   <li>{@link com.opcoach.bugsy.xtext.bugsDsl.ArrayFunction#getParams <em>Params</em>}</li>
 * </ul>
 *
 * @see com.opcoach.bugsy.xtext.bugsDsl.BugsDslPackage#getArrayFunction()
 * @model
 * @generated
 */
public interface ArrayFunction extends EObject
{
  /**
   * Returns the value of the '<em><b>Operation</b></em>' attribute.
   * The literals are from the enumeration {@link com.opcoach.bugsy.xtext.bugsDsl.ArrayOperator}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Operation</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operation</em>' attribute.
   * @see com.opcoach.bugsy.xtext.bugsDsl.ArrayOperator
   * @see #setOperation(ArrayOperator)
   * @see com.opcoach.bugsy.xtext.bugsDsl.BugsDslPackage#getArrayFunction_Operation()
   * @model
   * @generated
   */
  ArrayOperator getOperation();

  /**
   * Sets the value of the '{@link com.opcoach.bugsy.xtext.bugsDsl.ArrayFunction#getOperation <em>Operation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operation</em>' attribute.
   * @see com.opcoach.bugsy.xtext.bugsDsl.ArrayOperator
   * @see #getOperation()
   * @generated
   */
  void setOperation(ArrayOperator value);

  /**
   * Returns the value of the '<em><b>Params</b></em>' containment reference list.
   * The list contents are of type {@link com.opcoach.bugsy.xtext.bugsDsl.Expression}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Params</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' containment reference list.
   * @see com.opcoach.bugsy.xtext.bugsDsl.BugsDslPackage#getArrayFunction_Params()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getParams();

} // ArrayFunction
