/**
 * generated by Xtext 2.12.0
 */
package com.opcoach.bugsy.xtext.bugsDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see com.opcoach.bugsy.xtext.bugsDsl.BugsDslFactory
 * @model kind="package"
 * @generated
 */
public interface BugsDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "bugsDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.opcoach.com/bugsy/xtext/BugsDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "bugsDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BugsDslPackage eINSTANCE = com.opcoach.bugsy.xtext.bugsDsl.impl.BugsDslPackageImpl.init();

  /**
   * The meta object id for the '{@link com.opcoach.bugsy.xtext.bugsDsl.impl.BugsModelImpl <em>Bugs Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.opcoach.bugsy.xtext.bugsDsl.impl.BugsModelImpl
   * @see com.opcoach.bugsy.xtext.bugsDsl.impl.BugsDslPackageImpl#getBugsModel()
   * @generated
   */
  int BUGS_MODEL = 0;

  /**
   * The feature id for the '<em><b>Data</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUGS_MODEL__DATA = 0;

  /**
   * The feature id for the '<em><b>Instructions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUGS_MODEL__INSTRUCTIONS = 1;

  /**
   * The number of structural features of the '<em>Bugs Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUGS_MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.opcoach.bugsy.xtext.bugsDsl.impl.InstructionImpl <em>Instruction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.opcoach.bugsy.xtext.bugsDsl.impl.InstructionImpl
   * @see com.opcoach.bugsy.xtext.bugsDsl.impl.BugsDslPackageImpl#getInstruction()
   * @generated
   */
  int INSTRUCTION = 1;

  /**
   * The number of structural features of the '<em>Instruction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.opcoach.bugsy.xtext.bugsDsl.impl.ForImpl <em>For</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.opcoach.bugsy.xtext.bugsDsl.impl.ForImpl
   * @see com.opcoach.bugsy.xtext.bugsDsl.impl.BugsDslPackageImpl#getFor()
   * @generated
   */
  int FOR = 2;

  /**
   * The feature id for the '<em><b>Variable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR__VARIABLE = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Range</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR__RANGE = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Instructions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR__INSTRUCTIONS = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>For</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link com.opcoach.bugsy.xtext.bugsDsl.impl.ForRangeImpl <em>For Range</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.opcoach.bugsy.xtext.bugsDsl.impl.ForRangeImpl
   * @see com.opcoach.bugsy.xtext.bugsDsl.impl.BugsDslPackageImpl#getForRange()
   * @generated
   */
  int FOR_RANGE = 3;

  /**
   * The feature id for the '<em><b>Low</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_RANGE__LOW = 0;

  /**
   * The feature id for the '<em><b>High</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_RANGE__HIGH = 1;

  /**
   * The number of structural features of the '<em>For Range</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_RANGE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.opcoach.bugsy.xtext.bugsDsl.impl.ArrayRangeImpl <em>Array Range</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.opcoach.bugsy.xtext.bugsDsl.impl.ArrayRangeImpl
   * @see com.opcoach.bugsy.xtext.bugsDsl.impl.BugsDslPackageImpl#getArrayRange()
   * @generated
   */
  int ARRAY_RANGE = 4;

  /**
   * The feature id for the '<em><b>Low</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_RANGE__LOW = 0;

  /**
   * The feature id for the '<em><b>High</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_RANGE__HIGH = 1;

  /**
   * The number of structural features of the '<em>Array Range</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_RANGE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.opcoach.bugsy.xtext.bugsDsl.impl.ValueImpl <em>Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.opcoach.bugsy.xtext.bugsDsl.impl.ValueImpl
   * @see com.opcoach.bugsy.xtext.bugsDsl.impl.BugsDslPackageImpl#getValue()
   * @generated
   */
  int VALUE = 5;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE__VALUE = 0;

  /**
   * The feature id for the '<em><b>Id</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE__ID = 1;

  /**
   * The number of structural features of the '<em>Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.opcoach.bugsy.xtext.bugsDsl.impl.ArrayIDImpl <em>Array ID</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.opcoach.bugsy.xtext.bugsDsl.impl.ArrayIDImpl
   * @see com.opcoach.bugsy.xtext.bugsDsl.impl.BugsDslPackageImpl#getArrayID()
   * @generated
   */
  int ARRAY_ID = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_ID__NAME = 0;

  /**
   * The feature id for the '<em><b>Indexes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_ID__INDEXES = 1;

  /**
   * The number of structural features of the '<em>Array ID</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_ID_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.opcoach.bugsy.xtext.bugsDsl.impl.RelationImpl <em>Relation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.opcoach.bugsy.xtext.bugsDsl.impl.RelationImpl
   * @see com.opcoach.bugsy.xtext.bugsDsl.impl.BugsDslPackageImpl#getRelation()
   * @generated
   */
  int RELATION = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION__NAME = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Relation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.opcoach.bugsy.xtext.bugsDsl.impl.StochasticRelationImpl <em>Stochastic Relation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.opcoach.bugsy.xtext.bugsDsl.impl.StochasticRelationImpl
   * @see com.opcoach.bugsy.xtext.bugsDsl.impl.BugsDslPackageImpl#getStochasticRelation()
   * @generated
   */
  int STOCHASTIC_RELATION = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STOCHASTIC_RELATION__NAME = RELATION__NAME;

  /**
   * The feature id for the '<em><b>Distrib</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STOCHASTIC_RELATION__DISTRIB = RELATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STOCHASTIC_RELATION__PARAMS = RELATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Stochastic Relation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STOCHASTIC_RELATION_FEATURE_COUNT = RELATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.opcoach.bugsy.xtext.bugsDsl.impl.DeterministicRelationImpl <em>Deterministic Relation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.opcoach.bugsy.xtext.bugsDsl.impl.DeterministicRelationImpl
   * @see com.opcoach.bugsy.xtext.bugsDsl.impl.BugsDslPackageImpl#getDeterministicRelation()
   * @generated
   */
  int DETERMINISTIC_RELATION = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DETERMINISTIC_RELATION__NAME = RELATION__NAME;

  /**
   * The feature id for the '<em><b>Expressions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DETERMINISTIC_RELATION__EXPRESSIONS = RELATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Deterministic Relation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DETERMINISTIC_RELATION_FEATURE_COUNT = RELATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link com.opcoach.bugsy.xtext.bugsDsl.impl.FunctionImpl <em>Function</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.opcoach.bugsy.xtext.bugsDsl.impl.FunctionImpl
   * @see com.opcoach.bugsy.xtext.bugsDsl.impl.BugsDslPackageImpl#getFunction()
   * @generated
   */
  int FUNCTION = 10;

  /**
   * The feature id for the '<em><b>Operation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__OPERATION = 0;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__PARAMS = 1;

  /**
   * The number of structural features of the '<em>Function</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.opcoach.bugsy.xtext.bugsDsl.impl.DistributionImpl <em>Distribution</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.opcoach.bugsy.xtext.bugsDsl.impl.DistributionImpl
   * @see com.opcoach.bugsy.xtext.bugsDsl.impl.BugsDslPackageImpl#getDistribution()
   * @generated
   */
  int DISTRIBUTION = 11;

  /**
   * The feature id for the '<em><b>Distrib</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISTRIBUTION__DISTRIB = 0;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISTRIBUTION__PARAMS = 1;

  /**
   * The number of structural features of the '<em>Distribution</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISTRIBUTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.opcoach.bugsy.xtext.bugsDsl.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.opcoach.bugsy.xtext.bugsDsl.impl.ExpressionImpl
   * @see com.opcoach.bugsy.xtext.bugsDsl.impl.BugsDslPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 12;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__LEFT = 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__OP = 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__RIGHT = 2;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__VALUE = 3;

  /**
   * The feature id for the '<em><b>Function</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__FUNCTION = 4;

  /**
   * The feature id for the '<em><b>Distribution</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__DISTRIBUTION = 5;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link com.opcoach.bugsy.xtext.bugsDsl.DistributionOperator <em>Distribution Operator</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.opcoach.bugsy.xtext.bugsDsl.DistributionOperator
   * @see com.opcoach.bugsy.xtext.bugsDsl.impl.BugsDslPackageImpl#getDistributionOperator()
   * @generated
   */
  int DISTRIBUTION_OPERATOR = 13;

  /**
   * The meta object id for the '{@link com.opcoach.bugsy.xtext.bugsDsl.Density <em>Density</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.opcoach.bugsy.xtext.bugsDsl.Density
   * @see com.opcoach.bugsy.xtext.bugsDsl.impl.BugsDslPackageImpl#getDensity()
   * @generated
   */
  int DENSITY = 14;

  /**
   * The meta object id for the '{@link com.opcoach.bugsy.xtext.bugsDsl.FunctionOperator <em>Function Operator</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.opcoach.bugsy.xtext.bugsDsl.FunctionOperator
   * @see com.opcoach.bugsy.xtext.bugsDsl.impl.BugsDslPackageImpl#getFunctionOperator()
   * @generated
   */
  int FUNCTION_OPERATOR = 15;


  /**
   * Returns the meta object for class '{@link com.opcoach.bugsy.xtext.bugsDsl.BugsModel <em>Bugs Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bugs Model</em>'.
   * @see com.opcoach.bugsy.xtext.bugsDsl.BugsModel
   * @generated
   */
  EClass getBugsModel();

  /**
   * Returns the meta object for the containment reference list '{@link com.opcoach.bugsy.xtext.bugsDsl.BugsModel#getData <em>Data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Data</em>'.
   * @see com.opcoach.bugsy.xtext.bugsDsl.BugsModel#getData()
   * @see #getBugsModel()
   * @generated
   */
  EReference getBugsModel_Data();

  /**
   * Returns the meta object for the containment reference list '{@link com.opcoach.bugsy.xtext.bugsDsl.BugsModel#getInstructions <em>Instructions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Instructions</em>'.
   * @see com.opcoach.bugsy.xtext.bugsDsl.BugsModel#getInstructions()
   * @see #getBugsModel()
   * @generated
   */
  EReference getBugsModel_Instructions();

  /**
   * Returns the meta object for class '{@link com.opcoach.bugsy.xtext.bugsDsl.Instruction <em>Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Instruction</em>'.
   * @see com.opcoach.bugsy.xtext.bugsDsl.Instruction
   * @generated
   */
  EClass getInstruction();

  /**
   * Returns the meta object for class '{@link com.opcoach.bugsy.xtext.bugsDsl.For <em>For</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>For</em>'.
   * @see com.opcoach.bugsy.xtext.bugsDsl.For
   * @generated
   */
  EClass getFor();

  /**
   * Returns the meta object for the attribute '{@link com.opcoach.bugsy.xtext.bugsDsl.For#getVariable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Variable</em>'.
   * @see com.opcoach.bugsy.xtext.bugsDsl.For#getVariable()
   * @see #getFor()
   * @generated
   */
  EAttribute getFor_Variable();

  /**
   * Returns the meta object for the containment reference '{@link com.opcoach.bugsy.xtext.bugsDsl.For#getRange <em>Range</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Range</em>'.
   * @see com.opcoach.bugsy.xtext.bugsDsl.For#getRange()
   * @see #getFor()
   * @generated
   */
  EReference getFor_Range();

  /**
   * Returns the meta object for the containment reference list '{@link com.opcoach.bugsy.xtext.bugsDsl.For#getInstructions <em>Instructions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Instructions</em>'.
   * @see com.opcoach.bugsy.xtext.bugsDsl.For#getInstructions()
   * @see #getFor()
   * @generated
   */
  EReference getFor_Instructions();

  /**
   * Returns the meta object for class '{@link com.opcoach.bugsy.xtext.bugsDsl.ForRange <em>For Range</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>For Range</em>'.
   * @see com.opcoach.bugsy.xtext.bugsDsl.ForRange
   * @generated
   */
  EClass getForRange();

  /**
   * Returns the meta object for the attribute '{@link com.opcoach.bugsy.xtext.bugsDsl.ForRange#getLow <em>Low</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Low</em>'.
   * @see com.opcoach.bugsy.xtext.bugsDsl.ForRange#getLow()
   * @see #getForRange()
   * @generated
   */
  EAttribute getForRange_Low();

  /**
   * Returns the meta object for the attribute '{@link com.opcoach.bugsy.xtext.bugsDsl.ForRange#getHigh <em>High</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>High</em>'.
   * @see com.opcoach.bugsy.xtext.bugsDsl.ForRange#getHigh()
   * @see #getForRange()
   * @generated
   */
  EAttribute getForRange_High();

  /**
   * Returns the meta object for class '{@link com.opcoach.bugsy.xtext.bugsDsl.ArrayRange <em>Array Range</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Array Range</em>'.
   * @see com.opcoach.bugsy.xtext.bugsDsl.ArrayRange
   * @generated
   */
  EClass getArrayRange();

  /**
   * Returns the meta object for the attribute '{@link com.opcoach.bugsy.xtext.bugsDsl.ArrayRange#getLow <em>Low</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Low</em>'.
   * @see com.opcoach.bugsy.xtext.bugsDsl.ArrayRange#getLow()
   * @see #getArrayRange()
   * @generated
   */
  EAttribute getArrayRange_Low();

  /**
   * Returns the meta object for the attribute '{@link com.opcoach.bugsy.xtext.bugsDsl.ArrayRange#getHigh <em>High</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>High</em>'.
   * @see com.opcoach.bugsy.xtext.bugsDsl.ArrayRange#getHigh()
   * @see #getArrayRange()
   * @generated
   */
  EAttribute getArrayRange_High();

  /**
   * Returns the meta object for class '{@link com.opcoach.bugsy.xtext.bugsDsl.Value <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Value</em>'.
   * @see com.opcoach.bugsy.xtext.bugsDsl.Value
   * @generated
   */
  EClass getValue();

  /**
   * Returns the meta object for the attribute '{@link com.opcoach.bugsy.xtext.bugsDsl.Value#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see com.opcoach.bugsy.xtext.bugsDsl.Value#getValue()
   * @see #getValue()
   * @generated
   */
  EAttribute getValue_Value();

  /**
   * Returns the meta object for the containment reference '{@link com.opcoach.bugsy.xtext.bugsDsl.Value#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Id</em>'.
   * @see com.opcoach.bugsy.xtext.bugsDsl.Value#getId()
   * @see #getValue()
   * @generated
   */
  EReference getValue_Id();

  /**
   * Returns the meta object for class '{@link com.opcoach.bugsy.xtext.bugsDsl.ArrayID <em>Array ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Array ID</em>'.
   * @see com.opcoach.bugsy.xtext.bugsDsl.ArrayID
   * @generated
   */
  EClass getArrayID();

  /**
   * Returns the meta object for the attribute '{@link com.opcoach.bugsy.xtext.bugsDsl.ArrayID#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.opcoach.bugsy.xtext.bugsDsl.ArrayID#getName()
   * @see #getArrayID()
   * @generated
   */
  EAttribute getArrayID_Name();

  /**
   * Returns the meta object for the containment reference list '{@link com.opcoach.bugsy.xtext.bugsDsl.ArrayID#getIndexes <em>Indexes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Indexes</em>'.
   * @see com.opcoach.bugsy.xtext.bugsDsl.ArrayID#getIndexes()
   * @see #getArrayID()
   * @generated
   */
  EReference getArrayID_Indexes();

  /**
   * Returns the meta object for class '{@link com.opcoach.bugsy.xtext.bugsDsl.Relation <em>Relation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Relation</em>'.
   * @see com.opcoach.bugsy.xtext.bugsDsl.Relation
   * @generated
   */
  EClass getRelation();

  /**
   * Returns the meta object for the containment reference '{@link com.opcoach.bugsy.xtext.bugsDsl.Relation#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Name</em>'.
   * @see com.opcoach.bugsy.xtext.bugsDsl.Relation#getName()
   * @see #getRelation()
   * @generated
   */
  EReference getRelation_Name();

  /**
   * Returns the meta object for class '{@link com.opcoach.bugsy.xtext.bugsDsl.StochasticRelation <em>Stochastic Relation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Stochastic Relation</em>'.
   * @see com.opcoach.bugsy.xtext.bugsDsl.StochasticRelation
   * @generated
   */
  EClass getStochasticRelation();

  /**
   * Returns the meta object for the attribute '{@link com.opcoach.bugsy.xtext.bugsDsl.StochasticRelation#getDistrib <em>Distrib</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Distrib</em>'.
   * @see com.opcoach.bugsy.xtext.bugsDsl.StochasticRelation#getDistrib()
   * @see #getStochasticRelation()
   * @generated
   */
  EAttribute getStochasticRelation_Distrib();

  /**
   * Returns the meta object for the containment reference list '{@link com.opcoach.bugsy.xtext.bugsDsl.StochasticRelation#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see com.opcoach.bugsy.xtext.bugsDsl.StochasticRelation#getParams()
   * @see #getStochasticRelation()
   * @generated
   */
  EReference getStochasticRelation_Params();

  /**
   * Returns the meta object for class '{@link com.opcoach.bugsy.xtext.bugsDsl.DeterministicRelation <em>Deterministic Relation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Deterministic Relation</em>'.
   * @see com.opcoach.bugsy.xtext.bugsDsl.DeterministicRelation
   * @generated
   */
  EClass getDeterministicRelation();

  /**
   * Returns the meta object for the containment reference list '{@link com.opcoach.bugsy.xtext.bugsDsl.DeterministicRelation#getExpressions <em>Expressions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Expressions</em>'.
   * @see com.opcoach.bugsy.xtext.bugsDsl.DeterministicRelation#getExpressions()
   * @see #getDeterministicRelation()
   * @generated
   */
  EReference getDeterministicRelation_Expressions();

  /**
   * Returns the meta object for class '{@link com.opcoach.bugsy.xtext.bugsDsl.Function <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function</em>'.
   * @see com.opcoach.bugsy.xtext.bugsDsl.Function
   * @generated
   */
  EClass getFunction();

  /**
   * Returns the meta object for the attribute '{@link com.opcoach.bugsy.xtext.bugsDsl.Function#getOperation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operation</em>'.
   * @see com.opcoach.bugsy.xtext.bugsDsl.Function#getOperation()
   * @see #getFunction()
   * @generated
   */
  EAttribute getFunction_Operation();

  /**
   * Returns the meta object for the containment reference list '{@link com.opcoach.bugsy.xtext.bugsDsl.Function#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see com.opcoach.bugsy.xtext.bugsDsl.Function#getParams()
   * @see #getFunction()
   * @generated
   */
  EReference getFunction_Params();

  /**
   * Returns the meta object for class '{@link com.opcoach.bugsy.xtext.bugsDsl.Distribution <em>Distribution</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Distribution</em>'.
   * @see com.opcoach.bugsy.xtext.bugsDsl.Distribution
   * @generated
   */
  EClass getDistribution();

  /**
   * Returns the meta object for the attribute '{@link com.opcoach.bugsy.xtext.bugsDsl.Distribution#getDistrib <em>Distrib</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Distrib</em>'.
   * @see com.opcoach.bugsy.xtext.bugsDsl.Distribution#getDistrib()
   * @see #getDistribution()
   * @generated
   */
  EAttribute getDistribution_Distrib();

  /**
   * Returns the meta object for the containment reference list '{@link com.opcoach.bugsy.xtext.bugsDsl.Distribution#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see com.opcoach.bugsy.xtext.bugsDsl.Distribution#getParams()
   * @see #getDistribution()
   * @generated
   */
  EReference getDistribution_Params();

  /**
   * Returns the meta object for class '{@link com.opcoach.bugsy.xtext.bugsDsl.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see com.opcoach.bugsy.xtext.bugsDsl.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for the containment reference '{@link com.opcoach.bugsy.xtext.bugsDsl.Expression#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see com.opcoach.bugsy.xtext.bugsDsl.Expression#getLeft()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Left();

  /**
   * Returns the meta object for the attribute '{@link com.opcoach.bugsy.xtext.bugsDsl.Expression#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see com.opcoach.bugsy.xtext.bugsDsl.Expression#getOp()
   * @see #getExpression()
   * @generated
   */
  EAttribute getExpression_Op();

  /**
   * Returns the meta object for the containment reference '{@link com.opcoach.bugsy.xtext.bugsDsl.Expression#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see com.opcoach.bugsy.xtext.bugsDsl.Expression#getRight()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Right();

  /**
   * Returns the meta object for the containment reference '{@link com.opcoach.bugsy.xtext.bugsDsl.Expression#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see com.opcoach.bugsy.xtext.bugsDsl.Expression#getValue()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Value();

  /**
   * Returns the meta object for the containment reference '{@link com.opcoach.bugsy.xtext.bugsDsl.Expression#getFunction <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Function</em>'.
   * @see com.opcoach.bugsy.xtext.bugsDsl.Expression#getFunction()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Function();

  /**
   * Returns the meta object for the containment reference '{@link com.opcoach.bugsy.xtext.bugsDsl.Expression#getDistribution <em>Distribution</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Distribution</em>'.
   * @see com.opcoach.bugsy.xtext.bugsDsl.Expression#getDistribution()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Distribution();

  /**
   * Returns the meta object for enum '{@link com.opcoach.bugsy.xtext.bugsDsl.DistributionOperator <em>Distribution Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Distribution Operator</em>'.
   * @see com.opcoach.bugsy.xtext.bugsDsl.DistributionOperator
   * @generated
   */
  EEnum getDistributionOperator();

  /**
   * Returns the meta object for enum '{@link com.opcoach.bugsy.xtext.bugsDsl.Density <em>Density</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Density</em>'.
   * @see com.opcoach.bugsy.xtext.bugsDsl.Density
   * @generated
   */
  EEnum getDensity();

  /**
   * Returns the meta object for enum '{@link com.opcoach.bugsy.xtext.bugsDsl.FunctionOperator <em>Function Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Function Operator</em>'.
   * @see com.opcoach.bugsy.xtext.bugsDsl.FunctionOperator
   * @generated
   */
  EEnum getFunctionOperator();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  BugsDslFactory getBugsDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link com.opcoach.bugsy.xtext.bugsDsl.impl.BugsModelImpl <em>Bugs Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.opcoach.bugsy.xtext.bugsDsl.impl.BugsModelImpl
     * @see com.opcoach.bugsy.xtext.bugsDsl.impl.BugsDslPackageImpl#getBugsModel()
     * @generated
     */
    EClass BUGS_MODEL = eINSTANCE.getBugsModel();

    /**
     * The meta object literal for the '<em><b>Data</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BUGS_MODEL__DATA = eINSTANCE.getBugsModel_Data();

    /**
     * The meta object literal for the '<em><b>Instructions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BUGS_MODEL__INSTRUCTIONS = eINSTANCE.getBugsModel_Instructions();

    /**
     * The meta object literal for the '{@link com.opcoach.bugsy.xtext.bugsDsl.impl.InstructionImpl <em>Instruction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.opcoach.bugsy.xtext.bugsDsl.impl.InstructionImpl
     * @see com.opcoach.bugsy.xtext.bugsDsl.impl.BugsDslPackageImpl#getInstruction()
     * @generated
     */
    EClass INSTRUCTION = eINSTANCE.getInstruction();

    /**
     * The meta object literal for the '{@link com.opcoach.bugsy.xtext.bugsDsl.impl.ForImpl <em>For</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.opcoach.bugsy.xtext.bugsDsl.impl.ForImpl
     * @see com.opcoach.bugsy.xtext.bugsDsl.impl.BugsDslPackageImpl#getFor()
     * @generated
     */
    EClass FOR = eINSTANCE.getFor();

    /**
     * The meta object literal for the '<em><b>Variable</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FOR__VARIABLE = eINSTANCE.getFor_Variable();

    /**
     * The meta object literal for the '<em><b>Range</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR__RANGE = eINSTANCE.getFor_Range();

    /**
     * The meta object literal for the '<em><b>Instructions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR__INSTRUCTIONS = eINSTANCE.getFor_Instructions();

    /**
     * The meta object literal for the '{@link com.opcoach.bugsy.xtext.bugsDsl.impl.ForRangeImpl <em>For Range</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.opcoach.bugsy.xtext.bugsDsl.impl.ForRangeImpl
     * @see com.opcoach.bugsy.xtext.bugsDsl.impl.BugsDslPackageImpl#getForRange()
     * @generated
     */
    EClass FOR_RANGE = eINSTANCE.getForRange();

    /**
     * The meta object literal for the '<em><b>Low</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FOR_RANGE__LOW = eINSTANCE.getForRange_Low();

    /**
     * The meta object literal for the '<em><b>High</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FOR_RANGE__HIGH = eINSTANCE.getForRange_High();

    /**
     * The meta object literal for the '{@link com.opcoach.bugsy.xtext.bugsDsl.impl.ArrayRangeImpl <em>Array Range</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.opcoach.bugsy.xtext.bugsDsl.impl.ArrayRangeImpl
     * @see com.opcoach.bugsy.xtext.bugsDsl.impl.BugsDslPackageImpl#getArrayRange()
     * @generated
     */
    EClass ARRAY_RANGE = eINSTANCE.getArrayRange();

    /**
     * The meta object literal for the '<em><b>Low</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARRAY_RANGE__LOW = eINSTANCE.getArrayRange_Low();

    /**
     * The meta object literal for the '<em><b>High</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARRAY_RANGE__HIGH = eINSTANCE.getArrayRange_High();

    /**
     * The meta object literal for the '{@link com.opcoach.bugsy.xtext.bugsDsl.impl.ValueImpl <em>Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.opcoach.bugsy.xtext.bugsDsl.impl.ValueImpl
     * @see com.opcoach.bugsy.xtext.bugsDsl.impl.BugsDslPackageImpl#getValue()
     * @generated
     */
    EClass VALUE = eINSTANCE.getValue();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VALUE__VALUE = eINSTANCE.getValue_Value();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VALUE__ID = eINSTANCE.getValue_Id();

    /**
     * The meta object literal for the '{@link com.opcoach.bugsy.xtext.bugsDsl.impl.ArrayIDImpl <em>Array ID</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.opcoach.bugsy.xtext.bugsDsl.impl.ArrayIDImpl
     * @see com.opcoach.bugsy.xtext.bugsDsl.impl.BugsDslPackageImpl#getArrayID()
     * @generated
     */
    EClass ARRAY_ID = eINSTANCE.getArrayID();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARRAY_ID__NAME = eINSTANCE.getArrayID_Name();

    /**
     * The meta object literal for the '<em><b>Indexes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARRAY_ID__INDEXES = eINSTANCE.getArrayID_Indexes();

    /**
     * The meta object literal for the '{@link com.opcoach.bugsy.xtext.bugsDsl.impl.RelationImpl <em>Relation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.opcoach.bugsy.xtext.bugsDsl.impl.RelationImpl
     * @see com.opcoach.bugsy.xtext.bugsDsl.impl.BugsDslPackageImpl#getRelation()
     * @generated
     */
    EClass RELATION = eINSTANCE.getRelation();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATION__NAME = eINSTANCE.getRelation_Name();

    /**
     * The meta object literal for the '{@link com.opcoach.bugsy.xtext.bugsDsl.impl.StochasticRelationImpl <em>Stochastic Relation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.opcoach.bugsy.xtext.bugsDsl.impl.StochasticRelationImpl
     * @see com.opcoach.bugsy.xtext.bugsDsl.impl.BugsDslPackageImpl#getStochasticRelation()
     * @generated
     */
    EClass STOCHASTIC_RELATION = eINSTANCE.getStochasticRelation();

    /**
     * The meta object literal for the '<em><b>Distrib</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STOCHASTIC_RELATION__DISTRIB = eINSTANCE.getStochasticRelation_Distrib();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STOCHASTIC_RELATION__PARAMS = eINSTANCE.getStochasticRelation_Params();

    /**
     * The meta object literal for the '{@link com.opcoach.bugsy.xtext.bugsDsl.impl.DeterministicRelationImpl <em>Deterministic Relation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.opcoach.bugsy.xtext.bugsDsl.impl.DeterministicRelationImpl
     * @see com.opcoach.bugsy.xtext.bugsDsl.impl.BugsDslPackageImpl#getDeterministicRelation()
     * @generated
     */
    EClass DETERMINISTIC_RELATION = eINSTANCE.getDeterministicRelation();

    /**
     * The meta object literal for the '<em><b>Expressions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DETERMINISTIC_RELATION__EXPRESSIONS = eINSTANCE.getDeterministicRelation_Expressions();

    /**
     * The meta object literal for the '{@link com.opcoach.bugsy.xtext.bugsDsl.impl.FunctionImpl <em>Function</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.opcoach.bugsy.xtext.bugsDsl.impl.FunctionImpl
     * @see com.opcoach.bugsy.xtext.bugsDsl.impl.BugsDslPackageImpl#getFunction()
     * @generated
     */
    EClass FUNCTION = eINSTANCE.getFunction();

    /**
     * The meta object literal for the '<em><b>Operation</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCTION__OPERATION = eINSTANCE.getFunction_Operation();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION__PARAMS = eINSTANCE.getFunction_Params();

    /**
     * The meta object literal for the '{@link com.opcoach.bugsy.xtext.bugsDsl.impl.DistributionImpl <em>Distribution</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.opcoach.bugsy.xtext.bugsDsl.impl.DistributionImpl
     * @see com.opcoach.bugsy.xtext.bugsDsl.impl.BugsDslPackageImpl#getDistribution()
     * @generated
     */
    EClass DISTRIBUTION = eINSTANCE.getDistribution();

    /**
     * The meta object literal for the '<em><b>Distrib</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DISTRIBUTION__DISTRIB = eINSTANCE.getDistribution_Distrib();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DISTRIBUTION__PARAMS = eINSTANCE.getDistribution_Params();

    /**
     * The meta object literal for the '{@link com.opcoach.bugsy.xtext.bugsDsl.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.opcoach.bugsy.xtext.bugsDsl.impl.ExpressionImpl
     * @see com.opcoach.bugsy.xtext.bugsDsl.impl.BugsDslPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__LEFT = eINSTANCE.getExpression_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSION__OP = eINSTANCE.getExpression_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__RIGHT = eINSTANCE.getExpression_Right();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__VALUE = eINSTANCE.getExpression_Value();

    /**
     * The meta object literal for the '<em><b>Function</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__FUNCTION = eINSTANCE.getExpression_Function();

    /**
     * The meta object literal for the '<em><b>Distribution</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__DISTRIBUTION = eINSTANCE.getExpression_Distribution();

    /**
     * The meta object literal for the '{@link com.opcoach.bugsy.xtext.bugsDsl.DistributionOperator <em>Distribution Operator</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.opcoach.bugsy.xtext.bugsDsl.DistributionOperator
     * @see com.opcoach.bugsy.xtext.bugsDsl.impl.BugsDslPackageImpl#getDistributionOperator()
     * @generated
     */
    EEnum DISTRIBUTION_OPERATOR = eINSTANCE.getDistributionOperator();

    /**
     * The meta object literal for the '{@link com.opcoach.bugsy.xtext.bugsDsl.Density <em>Density</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.opcoach.bugsy.xtext.bugsDsl.Density
     * @see com.opcoach.bugsy.xtext.bugsDsl.impl.BugsDslPackageImpl#getDensity()
     * @generated
     */
    EEnum DENSITY = eINSTANCE.getDensity();

    /**
     * The meta object literal for the '{@link com.opcoach.bugsy.xtext.bugsDsl.FunctionOperator <em>Function Operator</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.opcoach.bugsy.xtext.bugsDsl.FunctionOperator
     * @see com.opcoach.bugsy.xtext.bugsDsl.impl.BugsDslPackageImpl#getFunctionOperator()
     * @generated
     */
    EEnum FUNCTION_OPERATOR = eINSTANCE.getFunctionOperator();

  }

} //BugsDslPackage
