/**
 * generated by Xtext 2.12.0
 */
package com.opcoach.bugsy.xtext.bugsDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.opcoach.bugsy.xtext.bugsDsl.Operation#getDistrib <em>Distrib</em>}</li>
 *   <li>{@link com.opcoach.bugsy.xtext.bugsDsl.Operation#getFunction <em>Function</em>}</li>
 *   <li>{@link com.opcoach.bugsy.xtext.bugsDsl.Operation#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see com.opcoach.bugsy.xtext.bugsDsl.BugsDslPackage#getOperation()
 * @model
 * @generated
 */
public interface Operation extends EObject
{
  /**
   * Returns the value of the '<em><b>Distrib</b></em>' attribute.
   * The literals are from the enumeration {@link com.opcoach.bugsy.xtext.bugsDsl.Distribution}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Distrib</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Distrib</em>' attribute.
   * @see com.opcoach.bugsy.xtext.bugsDsl.Distribution
   * @see #setDistrib(Distribution)
   * @see com.opcoach.bugsy.xtext.bugsDsl.BugsDslPackage#getOperation_Distrib()
   * @model
   * @generated
   */
  Distribution getDistrib();

  /**
   * Sets the value of the '{@link com.opcoach.bugsy.xtext.bugsDsl.Operation#getDistrib <em>Distrib</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Distrib</em>' attribute.
   * @see com.opcoach.bugsy.xtext.bugsDsl.Distribution
   * @see #getDistrib()
   * @generated
   */
  void setDistrib(Distribution value);

  /**
   * Returns the value of the '<em><b>Function</b></em>' attribute.
   * The literals are from the enumeration {@link com.opcoach.bugsy.xtext.bugsDsl.Function}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Function</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function</em>' attribute.
   * @see com.opcoach.bugsy.xtext.bugsDsl.Function
   * @see #setFunction(Function)
   * @see com.opcoach.bugsy.xtext.bugsDsl.BugsDslPackage#getOperation_Function()
   * @model
   * @generated
   */
  Function getFunction();

  /**
   * Sets the value of the '{@link com.opcoach.bugsy.xtext.bugsDsl.Operation#getFunction <em>Function</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Function</em>' attribute.
   * @see com.opcoach.bugsy.xtext.bugsDsl.Function
   * @see #getFunction()
   * @generated
   */
  void setFunction(Function value);

  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link com.opcoach.bugsy.xtext.bugsDsl.Parameter}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Elements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see com.opcoach.bugsy.xtext.bugsDsl.BugsDslPackage#getOperation_Elements()
   * @model containment="true"
   * @generated
   */
  EList<Parameter> getElements();

} // Operation
