/*
 * generated by Xtext 2.12.0
 */
package com.opcoach.bugsy.xtext.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.UnorderedGroup;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class BugsDslGrammarAccess extends AbstractGrammarElementFinder {
	
	public class BugsModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.opcoach.bugsy.xtext.BugsDsl.BugsModel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBugsModelAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cModelKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cInstructionsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cInstructionsInstructionParserRuleCall_3_0 = (RuleCall)cInstructionsAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//BugsModel:
		//	{BugsModel}
		//	'model' '{'
		//	instructions+=Instruction*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{BugsModel} 'model' '{' instructions+=Instruction* '}'
		public Group getGroup() { return cGroup; }
		
		//{BugsModel}
		public Action getBugsModelAction_0() { return cBugsModelAction_0; }
		
		//'model'
		public Keyword getModelKeyword_1() { return cModelKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//instructions+=Instruction*
		public Assignment getInstructionsAssignment_3() { return cInstructionsAssignment_3; }
		
		//Instruction
		public RuleCall getInstructionsInstructionParserRuleCall_3_0() { return cInstructionsInstructionParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class InstructionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.opcoach.bugsy.xtext.BugsDsl.Instruction");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cForParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cRelationParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		////.................................
		//// Starting grammar definition 
		////.................................
		//Instruction:
		//	For | Relation;
		@Override public ParserRule getRule() { return rule; }
		
		//For | Relation
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//For
		public RuleCall getForParserRuleCall_0() { return cForParserRuleCall_0; }
		
		//Relation
		public RuleCall getRelationParserRuleCall_1() { return cRelationParserRuleCall_1; }
	}
	public class ForElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.opcoach.bugsy.xtext.BugsDsl.For");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cForAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cForKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cVariableAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cVariableIDTerminalRuleCall_3_0 = (RuleCall)cVariableAssignment_3.eContents().get(0);
		private final Keyword cInKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cLowAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cLowINTTerminalRuleCall_5_0 = (RuleCall)cLowAssignment_5.eContents().get(0);
		private final Keyword cColonKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cHighAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cHighIDTerminalRuleCall_7_0 = (RuleCall)cHighAssignment_7.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cLeftCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cContentsAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cContentsInstructionParserRuleCall_10_0 = (RuleCall)cContentsAssignment_10.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//For:
		//	{For}
		//	'for' '(' variable=ID 'in' low=INT ':' high=ID ')' '{' contents+=Instruction* '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{For} 'for' '(' variable=ID 'in' low=INT ':' high=ID ')' '{' contents+=Instruction* '}'
		public Group getGroup() { return cGroup; }
		
		//{For}
		public Action getForAction_0() { return cForAction_0; }
		
		//'for'
		public Keyword getForKeyword_1() { return cForKeyword_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }
		
		//variable=ID
		public Assignment getVariableAssignment_3() { return cVariableAssignment_3; }
		
		//ID
		public RuleCall getVariableIDTerminalRuleCall_3_0() { return cVariableIDTerminalRuleCall_3_0; }
		
		//'in'
		public Keyword getInKeyword_4() { return cInKeyword_4; }
		
		//low=INT
		public Assignment getLowAssignment_5() { return cLowAssignment_5; }
		
		//INT
		public RuleCall getLowINTTerminalRuleCall_5_0() { return cLowINTTerminalRuleCall_5_0; }
		
		//':'
		public Keyword getColonKeyword_6() { return cColonKeyword_6; }
		
		//high=ID
		public Assignment getHighAssignment_7() { return cHighAssignment_7; }
		
		//ID
		public RuleCall getHighIDTerminalRuleCall_7_0() { return cHighIDTerminalRuleCall_7_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_8() { return cRightParenthesisKeyword_8; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_9() { return cLeftCurlyBracketKeyword_9; }
		
		//contents+=Instruction*
		public Assignment getContentsAssignment_10() { return cContentsAssignment_10; }
		
		//Instruction
		public RuleCall getContentsInstructionParserRuleCall_10_0() { return cContentsInstructionParserRuleCall_10_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}
	public class ParametersElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.opcoach.bugsy.xtext.BugsDsl.Parameters");
		private final Action cParametersAction = (Action)rule.eContents().get(1);
		
		//Parameters:
		//	{Parameters};
		@Override public ParserRule getRule() { return rule; }
		
		//{Parameters}
		public Action getParametersAction() { return cParametersAction; }
	}
	public class NumericElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.opcoach.bugsy.xtext.BugsDsl.Numeric");
		private final RuleCall cINTTerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Numeric:
		//	INT;
		@Override public ParserRule getRule() { return rule; }
		
		//INT
		public RuleCall getINTTerminalRuleCall() { return cINTTerminalRuleCall; }
	}
	public class ValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.opcoach.bugsy.xtext.BugsDsl.Value");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cNumericParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//// | FLOAT;
		//Value:
		//	Numeric | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//Numeric | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Numeric
		public RuleCall getNumericParserRuleCall_0() { return cNumericParserRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class ParameterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.opcoach.bugsy.xtext.BugsDsl.Parameter");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cParameterAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cValueAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cValueValueParserRuleCall_1_0 = (RuleCall)cValueAssignment_1.eContents().get(0);
		
		//Parameter:
		//	{Parameter} value=Value;
		@Override public ParserRule getRule() { return rule; }
		
		//{Parameter} value=Value
		public Group getGroup() { return cGroup; }
		
		//{Parameter}
		public Action getParameterAction_0() { return cParameterAction_0; }
		
		//value=Value
		public Assignment getValueAssignment_1() { return cValueAssignment_1; }
		
		//Value
		public RuleCall getValueValueParserRuleCall_1_0() { return cValueValueParserRuleCall_1_0; }
	}
	public class RelationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.opcoach.bugsy.xtext.BugsDsl.Relation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Assignment cRelationAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Alternatives cRelationAlternatives_1_0 = (Alternatives)cRelationAssignment_1.eContents().get(0);
		private final RuleCall cRelationStochasticRelationParserRuleCall_1_0_0 = (RuleCall)cRelationAlternatives_1_0.eContents().get(0);
		private final RuleCall cRelationDeterministicRelationParserRuleCall_1_0_1 = (RuleCall)cRelationAlternatives_1_0.eContents().get(1);
		
		//Relation:
		//	name=ID relation=(StochasticRelation | DeterministicRelation);
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID relation=(StochasticRelation | DeterministicRelation)
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//relation=(StochasticRelation | DeterministicRelation)
		public Assignment getRelationAssignment_1() { return cRelationAssignment_1; }
		
		//(StochasticRelation | DeterministicRelation)
		public Alternatives getRelationAlternatives_1_0() { return cRelationAlternatives_1_0; }
		
		//StochasticRelation
		public RuleCall getRelationStochasticRelationParserRuleCall_1_0_0() { return cRelationStochasticRelationParserRuleCall_1_0_0; }
		
		//DeterministicRelation
		public RuleCall getRelationDeterministicRelationParserRuleCall_1_0_1() { return cRelationDeterministicRelationParserRuleCall_1_0_1; }
	}
	public class StochasticRelationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.opcoach.bugsy.xtext.BugsDsl.StochasticRelation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cStochasticRelationAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cTildeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cDistribAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cDistribDensityEnumRuleCall_2_0 = (RuleCall)cDistribAssignment_2.eContents().get(0);
		private final Alternatives cAlternatives_3 = (Alternatives)cGroup.eContents().get(3);
		private final Keyword cLeftParenthesisRightParenthesisKeyword_3_0 = (Keyword)cAlternatives_3.eContents().get(0);
		private final Group cGroup_3_1 = (Group)cAlternatives_3.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_3_1_0 = (Keyword)cGroup_3_1.eContents().get(0);
		private final Group cGroup_3_1_1 = (Group)cGroup_3_1.eContents().get(1);
		private final Assignment cParamsAssignment_3_1_1_0 = (Assignment)cGroup_3_1_1.eContents().get(0);
		private final RuleCall cParamsParameterParserRuleCall_3_1_1_0_0 = (RuleCall)cParamsAssignment_3_1_1_0.eContents().get(0);
		private final Group cGroup_3_1_1_1 = (Group)cGroup_3_1_1.eContents().get(1);
		private final Keyword cCommaKeyword_3_1_1_1_0 = (Keyword)cGroup_3_1_1_1.eContents().get(0);
		private final Assignment cParamsAssignment_3_1_1_1_1 = (Assignment)cGroup_3_1_1_1.eContents().get(1);
		private final RuleCall cParamsParameterParserRuleCall_3_1_1_1_1_0 = (RuleCall)cParamsAssignment_3_1_1_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3_1_2 = (Keyword)cGroup_3_1.eContents().get(2);
		
		//StochasticRelation:
		//	{StochasticRelation}
		//	/* name=ID(dim=ARRAYDIM)? */ '~' distrib=Density ('()' | '(' (params+=Parameter (',' params+=Parameter)*) ')')?;
		@Override public ParserRule getRule() { return rule; }
		
		//{StochasticRelation} /* name=ID(dim=ARRAYDIM)? */ '~' distrib=Density ('()' | '(' (params+=Parameter (','
		//params+=Parameter)*) ')')?
		public Group getGroup() { return cGroup; }
		
		//{StochasticRelation}
		public Action getStochasticRelationAction_0() { return cStochasticRelationAction_0; }
		
		///* name=ID(dim=ARRAYDIM)? */ '~'
		public Keyword getTildeKeyword_1() { return cTildeKeyword_1; }
		
		//distrib=Density
		public Assignment getDistribAssignment_2() { return cDistribAssignment_2; }
		
		//Density
		public RuleCall getDistribDensityEnumRuleCall_2_0() { return cDistribDensityEnumRuleCall_2_0; }
		
		//('()' | '(' (params+=Parameter (',' params+=Parameter)*) ')')?
		public Alternatives getAlternatives_3() { return cAlternatives_3; }
		
		//'()'
		public Keyword getLeftParenthesisRightParenthesisKeyword_3_0() { return cLeftParenthesisRightParenthesisKeyword_3_0; }
		
		//'(' (params+=Parameter (',' params+=Parameter)*) ')'
		public Group getGroup_3_1() { return cGroup_3_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_3_1_0() { return cLeftParenthesisKeyword_3_1_0; }
		
		//params+=Parameter (',' params+=Parameter)*
		public Group getGroup_3_1_1() { return cGroup_3_1_1; }
		
		//params+=Parameter
		public Assignment getParamsAssignment_3_1_1_0() { return cParamsAssignment_3_1_1_0; }
		
		//Parameter
		public RuleCall getParamsParameterParserRuleCall_3_1_1_0_0() { return cParamsParameterParserRuleCall_3_1_1_0_0; }
		
		//(',' params+=Parameter)*
		public Group getGroup_3_1_1_1() { return cGroup_3_1_1_1; }
		
		//','
		public Keyword getCommaKeyword_3_1_1_1_0() { return cCommaKeyword_3_1_1_1_0; }
		
		//params+=Parameter
		public Assignment getParamsAssignment_3_1_1_1_1() { return cParamsAssignment_3_1_1_1_1; }
		
		//Parameter
		public RuleCall getParamsParameterParserRuleCall_3_1_1_1_1_0() { return cParamsParameterParserRuleCall_3_1_1_1_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3_1_2() { return cRightParenthesisKeyword_3_1_2; }
	}
	public class DeterministicRelationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.opcoach.bugsy.xtext.BugsDsl.DeterministicRelation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cDeterministicRelationAction_0 = (Action)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Keyword cLessThanSignHyphenMinusKeyword_1_0 = (Keyword)cAlternatives_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1_1 = (Keyword)cAlternatives_1.eContents().get(1);
		private final UnorderedGroup cUnorderedGroup_2 = (UnorderedGroup)cGroup.eContents().get(2);
		private final Assignment cDistribAssignment_2_0 = (Assignment)cUnorderedGroup_2.eContents().get(0);
		private final RuleCall cDistribDistributionEnumRuleCall_2_0_0 = (RuleCall)cDistribAssignment_2_0.eContents().get(0);
		private final Assignment cFunctionAssignment_2_1 = (Assignment)cUnorderedGroup_2.eContents().get(1);
		private final RuleCall cFunctionFunctionEnumRuleCall_2_1_0 = (RuleCall)cFunctionAssignment_2_1.eContents().get(0);
		private final Alternatives cAlternatives_3 = (Alternatives)cGroup.eContents().get(3);
		private final Keyword cLeftParenthesisRightParenthesisKeyword_3_0 = (Keyword)cAlternatives_3.eContents().get(0);
		private final Group cGroup_3_1 = (Group)cAlternatives_3.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_3_1_0 = (Keyword)cGroup_3_1.eContents().get(0);
		private final Group cGroup_3_1_1 = (Group)cGroup_3_1.eContents().get(1);
		private final Assignment cParamsAssignment_3_1_1_0 = (Assignment)cGroup_3_1_1.eContents().get(0);
		private final RuleCall cParamsParameterParserRuleCall_3_1_1_0_0 = (RuleCall)cParamsAssignment_3_1_1_0.eContents().get(0);
		private final Group cGroup_3_1_1_1 = (Group)cGroup_3_1_1.eContents().get(1);
		private final Keyword cCommaKeyword_3_1_1_1_0 = (Keyword)cGroup_3_1_1_1.eContents().get(0);
		private final Assignment cParamsAssignment_3_1_1_1_1 = (Assignment)cGroup_3_1_1_1.eContents().get(1);
		private final RuleCall cParamsParameterParserRuleCall_3_1_1_1_1_0 = (RuleCall)cParamsAssignment_3_1_1_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3_1_1_2 = (Keyword)cGroup_3_1_1.eContents().get(2);
		
		//DeterministicRelation:
		//	{DeterministicRelation} ('<-' | '=') (distrib=Distribution? & function=Function?) ('()' | '(' (params+=Parameter (','
		//	params+=Parameter)* ')')?);
		@Override public ParserRule getRule() { return rule; }
		
		//{DeterministicRelation} ('<-' | '=') (distrib=Distribution? & function=Function?) ('()' | '(' (params+=Parameter (','
		//params+=Parameter)* ')')?)
		public Group getGroup() { return cGroup; }
		
		//{DeterministicRelation}
		public Action getDeterministicRelationAction_0() { return cDeterministicRelationAction_0; }
		
		///* name=ID  (dim=ARRAYDIM)? */ '<-' | '='
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//'<-'
		public Keyword getLessThanSignHyphenMinusKeyword_1_0() { return cLessThanSignHyphenMinusKeyword_1_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_1_1() { return cEqualsSignKeyword_1_1; }
		
		//distrib=Distribution? & function=Function?
		public UnorderedGroup getUnorderedGroup_2() { return cUnorderedGroup_2; }
		
		//distrib=Distribution?
		public Assignment getDistribAssignment_2_0() { return cDistribAssignment_2_0; }
		
		//Distribution
		public RuleCall getDistribDistributionEnumRuleCall_2_0_0() { return cDistribDistributionEnumRuleCall_2_0_0; }
		
		//function=Function?
		public Assignment getFunctionAssignment_2_1() { return cFunctionAssignment_2_1; }
		
		//Function
		public RuleCall getFunctionFunctionEnumRuleCall_2_1_0() { return cFunctionFunctionEnumRuleCall_2_1_0; }
		
		//'()' | '(' (params+=Parameter (',' params+=Parameter)* ')')?
		public Alternatives getAlternatives_3() { return cAlternatives_3; }
		
		//'()'
		public Keyword getLeftParenthesisRightParenthesisKeyword_3_0() { return cLeftParenthesisRightParenthesisKeyword_3_0; }
		
		//'(' (params+=Parameter (',' params+=Parameter)* ')')?
		public Group getGroup_3_1() { return cGroup_3_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_3_1_0() { return cLeftParenthesisKeyword_3_1_0; }
		
		//(params+=Parameter (',' params+=Parameter)* ')')?
		public Group getGroup_3_1_1() { return cGroup_3_1_1; }
		
		//params+=Parameter
		public Assignment getParamsAssignment_3_1_1_0() { return cParamsAssignment_3_1_1_0; }
		
		//Parameter
		public RuleCall getParamsParameterParserRuleCall_3_1_1_0_0() { return cParamsParameterParserRuleCall_3_1_1_0_0; }
		
		//(',' params+=Parameter)*
		public Group getGroup_3_1_1_1() { return cGroup_3_1_1_1; }
		
		//','
		public Keyword getCommaKeyword_3_1_1_1_0() { return cCommaKeyword_3_1_1_1_0; }
		
		//params+=Parameter
		public Assignment getParamsAssignment_3_1_1_1_1() { return cParamsAssignment_3_1_1_1_1; }
		
		//Parameter
		public RuleCall getParamsParameterParserRuleCall_3_1_1_1_1_0() { return cParamsParameterParserRuleCall_3_1_1_1_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3_1_1_2() { return cRightParenthesisKeyword_3_1_1_2; }
	}
	
	public class DistributionElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "com.opcoach.bugsy.xtext.BugsDsl.Distribution");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cDbernEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cDbernDbernKeyword_0_0 = (Keyword)cDbernEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cDbinEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cDbinDbinKeyword_1_0 = (Keyword)cDbinEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cDchisqrEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cDchisqrDchisqrKeyword_2_0 = (Keyword)cDchisqrEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cDdexpEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cDdexpDdexpKeyword_3_0 = (Keyword)cDdexpEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cDexpEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cDexpDexpKeyword_4_0 = (Keyword)cDexpEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cDfEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cDfDfKeyword_5_0 = (Keyword)cDfEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cDgammaEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cDgammaDgammaKeyword_6_0 = (Keyword)cDgammaEnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cDgengammEnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cDgengammDgenGammaKeyword_7_0 = (Keyword)cDgengammEnumLiteralDeclaration_7.eContents().get(0);
		private final EnumLiteralDeclaration cDhyperEnumLiteralDeclaration_8 = (EnumLiteralDeclaration)cAlternatives.eContents().get(8);
		private final Keyword cDhyperDhyperKeyword_8_0 = (Keyword)cDhyperEnumLiteralDeclaration_8.eContents().get(0);
		private final EnumLiteralDeclaration cDlogisEnumLiteralDeclaration_9 = (EnumLiteralDeclaration)cAlternatives.eContents().get(9);
		private final Keyword cDlogisDlogisKeyword_9_0 = (Keyword)cDlogisEnumLiteralDeclaration_9.eContents().get(0);
		private final EnumLiteralDeclaration cDlnormEnumLiteralDeclaration_10 = (EnumLiteralDeclaration)cAlternatives.eContents().get(10);
		private final Keyword cDlnormDlnormKeyword_10_0 = (Keyword)cDlnormEnumLiteralDeclaration_10.eContents().get(0);
		private final EnumLiteralDeclaration cDnegbinEnumLiteralDeclaration_11 = (EnumLiteralDeclaration)cAlternatives.eContents().get(11);
		private final Keyword cDnegbinDnegbinKeyword_11_0 = (Keyword)cDnegbinEnumLiteralDeclaration_11.eContents().get(0);
		private final EnumLiteralDeclaration cDnchisqrEnumLiteralDeclaration_12 = (EnumLiteralDeclaration)cAlternatives.eContents().get(12);
		private final Keyword cDnchisqrDnchisqrKeyword_12_0 = (Keyword)cDnchisqrEnumLiteralDeclaration_12.eContents().get(0);
		private final EnumLiteralDeclaration cDparEnumLiteralDeclaration_13 = (EnumLiteralDeclaration)cAlternatives.eContents().get(13);
		private final Keyword cDparDparKeyword_13_0 = (Keyword)cDparEnumLiteralDeclaration_13.eContents().get(0);
		private final EnumLiteralDeclaration cDpoisEnumLiteralDeclaration_14 = (EnumLiteralDeclaration)cAlternatives.eContents().get(14);
		private final Keyword cDpoisDpoisKeyword_14_0 = (Keyword)cDpoisEnumLiteralDeclaration_14.eContents().get(0);
		private final EnumLiteralDeclaration cDtEnumLiteralDeclaration_15 = (EnumLiteralDeclaration)cAlternatives.eContents().get(15);
		private final Keyword cDtDtKeyword_15_0 = (Keyword)cDtEnumLiteralDeclaration_15.eContents().get(0);
		private final EnumLiteralDeclaration cDweibEnumLiteralDeclaration_16 = (EnumLiteralDeclaration)cAlternatives.eContents().get(16);
		private final Keyword cDweibDweibKeyword_16_0 = (Keyword)cDweibEnumLiteralDeclaration_16.eContents().get(0);
		
		//enum Distribution:
		//	dbern |
		//	dbin | dchisqr | ddexp |
		//	dexp | df |
		//	dgamma | dgengamm='dgen.gamma' | dhyper | dlogis | dlnorm | dnegbin |
		//	dnchisqr |
		//	dpar | dpois | dt | dweib;
		public EnumRule getRule() { return rule; }
		
		//dbern | dbin | dchisqr | ddexp | dexp | df | dgamma | dgengamm='dgen.gamma' | dhyper | dlogis | dlnorm | dnegbin |
		//dnchisqr | dpar | dpois | dt | dweib
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//dbern
		public EnumLiteralDeclaration getDbernEnumLiteralDeclaration_0() { return cDbernEnumLiteralDeclaration_0; }
		
		//'dbern'
		public Keyword getDbernDbernKeyword_0_0() { return cDbernDbernKeyword_0_0; }
		
		//dbin
		public EnumLiteralDeclaration getDbinEnumLiteralDeclaration_1() { return cDbinEnumLiteralDeclaration_1; }
		
		//'dbin'
		public Keyword getDbinDbinKeyword_1_0() { return cDbinDbinKeyword_1_0; }
		
		//dchisqr
		public EnumLiteralDeclaration getDchisqrEnumLiteralDeclaration_2() { return cDchisqrEnumLiteralDeclaration_2; }
		
		//'dchisqr'
		public Keyword getDchisqrDchisqrKeyword_2_0() { return cDchisqrDchisqrKeyword_2_0; }
		
		//ddexp
		public EnumLiteralDeclaration getDdexpEnumLiteralDeclaration_3() { return cDdexpEnumLiteralDeclaration_3; }
		
		//'ddexp'
		public Keyword getDdexpDdexpKeyword_3_0() { return cDdexpDdexpKeyword_3_0; }
		
		//dexp
		public EnumLiteralDeclaration getDexpEnumLiteralDeclaration_4() { return cDexpEnumLiteralDeclaration_4; }
		
		//'dexp'
		public Keyword getDexpDexpKeyword_4_0() { return cDexpDexpKeyword_4_0; }
		
		//df
		public EnumLiteralDeclaration getDfEnumLiteralDeclaration_5() { return cDfEnumLiteralDeclaration_5; }
		
		//'df'
		public Keyword getDfDfKeyword_5_0() { return cDfDfKeyword_5_0; }
		
		//dgamma
		public EnumLiteralDeclaration getDgammaEnumLiteralDeclaration_6() { return cDgammaEnumLiteralDeclaration_6; }
		
		//'dgamma'
		public Keyword getDgammaDgammaKeyword_6_0() { return cDgammaDgammaKeyword_6_0; }
		
		//dgengamm='dgen.gamma'
		public EnumLiteralDeclaration getDgengammEnumLiteralDeclaration_7() { return cDgengammEnumLiteralDeclaration_7; }
		
		//'dgen.gamma'
		public Keyword getDgengammDgenGammaKeyword_7_0() { return cDgengammDgenGammaKeyword_7_0; }
		
		//dhyper
		public EnumLiteralDeclaration getDhyperEnumLiteralDeclaration_8() { return cDhyperEnumLiteralDeclaration_8; }
		
		//'dhyper'
		public Keyword getDhyperDhyperKeyword_8_0() { return cDhyperDhyperKeyword_8_0; }
		
		//dlogis
		public EnumLiteralDeclaration getDlogisEnumLiteralDeclaration_9() { return cDlogisEnumLiteralDeclaration_9; }
		
		//'dlogis'
		public Keyword getDlogisDlogisKeyword_9_0() { return cDlogisDlogisKeyword_9_0; }
		
		//dlnorm
		public EnumLiteralDeclaration getDlnormEnumLiteralDeclaration_10() { return cDlnormEnumLiteralDeclaration_10; }
		
		//'dlnorm'
		public Keyword getDlnormDlnormKeyword_10_0() { return cDlnormDlnormKeyword_10_0; }
		
		//dnegbin
		public EnumLiteralDeclaration getDnegbinEnumLiteralDeclaration_11() { return cDnegbinEnumLiteralDeclaration_11; }
		
		//'dnegbin'
		public Keyword getDnegbinDnegbinKeyword_11_0() { return cDnegbinDnegbinKeyword_11_0; }
		
		//dnchisqr
		public EnumLiteralDeclaration getDnchisqrEnumLiteralDeclaration_12() { return cDnchisqrEnumLiteralDeclaration_12; }
		
		//'dnchisqr'
		public Keyword getDnchisqrDnchisqrKeyword_12_0() { return cDnchisqrDnchisqrKeyword_12_0; }
		
		//dpar
		public EnumLiteralDeclaration getDparEnumLiteralDeclaration_13() { return cDparEnumLiteralDeclaration_13; }
		
		//'dpar'
		public Keyword getDparDparKeyword_13_0() { return cDparDparKeyword_13_0; }
		
		//dpois
		public EnumLiteralDeclaration getDpoisEnumLiteralDeclaration_14() { return cDpoisEnumLiteralDeclaration_14; }
		
		//'dpois'
		public Keyword getDpoisDpoisKeyword_14_0() { return cDpoisDpoisKeyword_14_0; }
		
		//dt
		public EnumLiteralDeclaration getDtEnumLiteralDeclaration_15() { return cDtEnumLiteralDeclaration_15; }
		
		//'dt'
		public Keyword getDtDtKeyword_15_0() { return cDtDtKeyword_15_0; }
		
		//dweib
		public EnumLiteralDeclaration getDweibEnumLiteralDeclaration_16() { return cDweibEnumLiteralDeclaration_16; }
		
		//'dweib'
		public Keyword getDweibDweibKeyword_16_0() { return cDweibDweibKeyword_16_0; }
	}
	public class DensityElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "com.opcoach.bugsy.xtext.BugsDsl.Density");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cDnormEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cDnormDnormKeyword_0_0 = (Keyword)cDnormEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cDunifEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cDunifDunifKeyword_1_0 = (Keyword)cDunifEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cDbetaEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cDbetaDbetaKeyword_2_0 = (Keyword)cDbetaEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum Density:
		//	dnorm |
		//	dunif |
		//	dbeta;
		public EnumRule getRule() { return rule; }
		
		//dnorm | dunif | dbeta
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//dnorm
		public EnumLiteralDeclaration getDnormEnumLiteralDeclaration_0() { return cDnormEnumLiteralDeclaration_0; }
		
		//'dnorm'
		public Keyword getDnormDnormKeyword_0_0() { return cDnormDnormKeyword_0_0; }
		
		//dunif
		public EnumLiteralDeclaration getDunifEnumLiteralDeclaration_1() { return cDunifEnumLiteralDeclaration_1; }
		
		//'dunif'
		public Keyword getDunifDunifKeyword_1_0() { return cDunifDunifKeyword_1_0; }
		
		//dbeta
		public EnumLiteralDeclaration getDbetaEnumLiteralDeclaration_2() { return cDbetaEnumLiteralDeclaration_2; }
		
		//'dbeta'
		public Keyword getDbetaDbetaKeyword_2_0() { return cDbetaDbetaKeyword_2_0; }
	}
	public class FunctionElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "com.opcoach.bugsy.xtext.BugsDsl.Function");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cAcosEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cAcosAcosKeyword_0_0 = (Keyword)cAcosEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cAcoshEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cAcoshAcoshKeyword_1_0 = (Keyword)cAcoshEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cAsinEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cAsinAsinKeyword_2_0 = (Keyword)cAsinEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cAsinhEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cAsinhAsinhKeyword_3_0 = (Keyword)cAsinhEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cAtanEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cAtanAtanKeyword_4_0 = (Keyword)cAtanEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cLogEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cLogLogKeyword_5_0 = (Keyword)cLogEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cEpEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cEpExpKeyword_6_0 = (Keyword)cEpEnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cCEnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cCCKeyword_7_0 = (Keyword)cCEnumLiteralDeclaration_7.eContents().get(0);
		
		//enum Function:
		//	acos | acosh | asin | asinh | atan | log | ep='exp' | c;
		public EnumRule getRule() { return rule; }
		
		//acos | acosh | asin | asinh | atan | log | ep='exp' | c
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//acos
		public EnumLiteralDeclaration getAcosEnumLiteralDeclaration_0() { return cAcosEnumLiteralDeclaration_0; }
		
		//'acos'
		public Keyword getAcosAcosKeyword_0_0() { return cAcosAcosKeyword_0_0; }
		
		//acosh
		public EnumLiteralDeclaration getAcoshEnumLiteralDeclaration_1() { return cAcoshEnumLiteralDeclaration_1; }
		
		//'acosh'
		public Keyword getAcoshAcoshKeyword_1_0() { return cAcoshAcoshKeyword_1_0; }
		
		//asin
		public EnumLiteralDeclaration getAsinEnumLiteralDeclaration_2() { return cAsinEnumLiteralDeclaration_2; }
		
		//'asin'
		public Keyword getAsinAsinKeyword_2_0() { return cAsinAsinKeyword_2_0; }
		
		//asinh
		public EnumLiteralDeclaration getAsinhEnumLiteralDeclaration_3() { return cAsinhEnumLiteralDeclaration_3; }
		
		//'asinh'
		public Keyword getAsinhAsinhKeyword_3_0() { return cAsinhAsinhKeyword_3_0; }
		
		//atan
		public EnumLiteralDeclaration getAtanEnumLiteralDeclaration_4() { return cAtanEnumLiteralDeclaration_4; }
		
		//'atan'
		public Keyword getAtanAtanKeyword_4_0() { return cAtanAtanKeyword_4_0; }
		
		//log
		public EnumLiteralDeclaration getLogEnumLiteralDeclaration_5() { return cLogEnumLiteralDeclaration_5; }
		
		//'log'
		public Keyword getLogLogKeyword_5_0() { return cLogLogKeyword_5_0; }
		
		//ep='exp'
		public EnumLiteralDeclaration getEpEnumLiteralDeclaration_6() { return cEpEnumLiteralDeclaration_6; }
		
		//'exp'
		public Keyword getEpExpKeyword_6_0() { return cEpExpKeyword_6_0; }
		
		//c
		public EnumLiteralDeclaration getCEnumLiteralDeclaration_7() { return cCEnumLiteralDeclaration_7; }
		
		//'c'
		public Keyword getCCKeyword_7_0() { return cCCKeyword_7_0; }
	}
	
	private final BugsModelElements pBugsModel;
	private final TerminalRule tSL_COMMENT;
	private final InstructionElements pInstruction;
	private final ForElements pFor;
	private final ParametersElements pParameters;
	private final NumericElements pNumeric;
	private final ValueElements pValue;
	private final ParameterElements pParameter;
	private final RelationElements pRelation;
	private final StochasticRelationElements pStochasticRelation;
	private final DeterministicRelationElements pDeterministicRelation;
	private final DistributionElements eDistribution;
	private final DensityElements eDensity;
	private final FunctionElements eFunction;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public BugsDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pBugsModel = new BugsModelElements();
		this.tSL_COMMENT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "com.opcoach.bugsy.xtext.BugsDsl.SL_COMMENT");
		this.pInstruction = new InstructionElements();
		this.pFor = new ForElements();
		this.pParameters = new ParametersElements();
		this.pNumeric = new NumericElements();
		this.pValue = new ValueElements();
		this.pParameter = new ParameterElements();
		this.pRelation = new RelationElements();
		this.pStochasticRelation = new StochasticRelationElements();
		this.pDeterministicRelation = new DeterministicRelationElements();
		this.eDistribution = new DistributionElements();
		this.eDensity = new DensityElements();
		this.eFunction = new FunctionElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("com.opcoach.bugsy.xtext.BugsDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//BugsModel:
	//	{BugsModel}
	//	'model' '{'
	//	instructions+=Instruction*
	//	'}';
	public BugsModelElements getBugsModelAccess() {
		return pBugsModel;
	}
	
	public ParserRule getBugsModelRule() {
		return getBugsModelAccess().getRule();
	}
	
	//@ Override terminal SL_COMMENT:
	//	'#' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return tSL_COMMENT;
	}
	
	////.................................
	//// Starting grammar definition 
	////.................................
	//Instruction:
	//	For | Relation;
	public InstructionElements getInstructionAccess() {
		return pInstruction;
	}
	
	public ParserRule getInstructionRule() {
		return getInstructionAccess().getRule();
	}
	
	//For:
	//	{For}
	//	'for' '(' variable=ID 'in' low=INT ':' high=ID ')' '{' contents+=Instruction* '}';
	public ForElements getForAccess() {
		return pFor;
	}
	
	public ParserRule getForRule() {
		return getForAccess().getRule();
	}
	
	//Parameters:
	//	{Parameters};
	public ParametersElements getParametersAccess() {
		return pParameters;
	}
	
	public ParserRule getParametersRule() {
		return getParametersAccess().getRule();
	}
	
	//Numeric:
	//	INT;
	public NumericElements getNumericAccess() {
		return pNumeric;
	}
	
	public ParserRule getNumericRule() {
		return getNumericAccess().getRule();
	}
	
	//// | FLOAT;
	//Value:
	//	Numeric | ID;
	public ValueElements getValueAccess() {
		return pValue;
	}
	
	public ParserRule getValueRule() {
		return getValueAccess().getRule();
	}
	
	//Parameter:
	//	{Parameter} value=Value;
	public ParameterElements getParameterAccess() {
		return pParameter;
	}
	
	public ParserRule getParameterRule() {
		return getParameterAccess().getRule();
	}
	
	//Relation:
	//	name=ID relation=(StochasticRelation | DeterministicRelation);
	public RelationElements getRelationAccess() {
		return pRelation;
	}
	
	public ParserRule getRelationRule() {
		return getRelationAccess().getRule();
	}
	
	//StochasticRelation:
	//	{StochasticRelation}
	//	/* name=ID(dim=ARRAYDIM)? */ '~' distrib=Density ('()' | '(' (params+=Parameter (',' params+=Parameter)*) ')')?;
	public StochasticRelationElements getStochasticRelationAccess() {
		return pStochasticRelation;
	}
	
	public ParserRule getStochasticRelationRule() {
		return getStochasticRelationAccess().getRule();
	}
	
	//DeterministicRelation:
	//	{DeterministicRelation} ('<-' | '=') (distrib=Distribution? & function=Function?) ('()' | '(' (params+=Parameter (','
	//	params+=Parameter)* ')')?);
	public DeterministicRelationElements getDeterministicRelationAccess() {
		return pDeterministicRelation;
	}
	
	public ParserRule getDeterministicRelationRule() {
		return getDeterministicRelationAccess().getRule();
	}
	
	//enum Distribution:
	//	dbern |
	//	dbin | dchisqr | ddexp |
	//	dexp | df |
	//	dgamma | dgengamm='dgen.gamma' | dhyper | dlogis | dlnorm | dnegbin |
	//	dnchisqr |
	//	dpar | dpois | dt | dweib;
	public DistributionElements getDistributionAccess() {
		return eDistribution;
	}
	
	public EnumRule getDistributionRule() {
		return getDistributionAccess().getRule();
	}
	
	//enum Density:
	//	dnorm |
	//	dunif |
	//	dbeta;
	public DensityElements getDensityAccess() {
		return eDensity;
	}
	
	public EnumRule getDensityRule() {
		return getDensityAccess().getRule();
	}
	
	//enum Function:
	//	acos | acosh | asin | asinh | atan | log | ep='exp' | c;
	public FunctionElements getFunctionAccess() {
		return eFunction;
	}
	
	public EnumRule getFunctionRule() {
		return getFunctionAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
