/*
 * generated by Xtext 2.12.0
 */
package com.opcoach.bugsy.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBugsDslScopeProvider extends DelegatingScopeProvider {
}
