/*
 * generated by Xtext 2.12.0
 */
package com.opcoach.bugsy.xtext.tests

import com.google.inject.Inject
import com.opcoach.bugsy.xtext.bugsDsl.BugsModel
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.eclipse.xtext.testing.validation.ValidationTestHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import com.opcoach.bugsy.xtext.bugsDsl.BugsDslPackage
import com.opcoach.bugsy.xtext.validation.BugsDslValidator

@RunWith(XtextRunner)
@InjectWith(BugsDslInjectorProvider)
class BugsDslValidationTest {

	@Inject
	extension ParseHelper<BugsModel> parseHelper
	@Inject 
	extension ValidationTestHelper validHelper

	@Test   // For issue #15
	def void testIssue15_UniqueIdentifier() {
		'''model{
		for(j in 1:M){
		for(i in 1:N){
		a[j,i] ~ dnorm(mu,tau)
		}
		}
		tau ~ dgamma(0.01,0.01)
		mu ~ dnorm(0,1) 
		mu ~ dnorm(5,10)
		}'''.parse.assertWarning(BugsDslPackage::eINSTANCE.relation, BugsDslValidator::UNIQUE_VARIABLE_NAME)
		
	}

	

}
